apiVersion: v1
kind: ReplicationController
metadata:
  name: relicapod
spec:
  replicas: 2
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rc-Service
spec:
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
    nodeport: 12345
  type: NodePort    

